# Generated by Django 6.0 on 2026-01-10 08:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gifts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='gift',
            name='visible_in',
            field=models.ManyToManyField(blank=True, related_name='visible_gifts', to='gifts.group'),
        ),
    ]
