# Generated by Django 6.0 on 2025-12-12 16:20
from django.contrib.auth.hashers import make_password
from django.db import migrations

def hash_passwords(apps, schema_editor):
    Person = apps.get_model('gifts', 'Person')
    updated_count = 0
    for person in Person.objects.all():
        if person.password and not person.password.startswith('pbkdf2_sha256$'):  # Vérifie si ce n'est pas déjà haché (les hachages Django commencent par ça)
            person.password = make_password(person.password)
            person.save()
            updated_count += 1
    if updated_count > 0:
        print(f"{updated_count} mots de passe ont été hachés.")


class Migration(migrations.Migration):

    dependencies = [
        ('gifts', '0002_alter_person_password_length'),
    ]

    operations = [
        migrations.RunPython(hash_passwords),
    ]
