# Generated by Django 6.0 on 2025-12-16 20:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gifts', '0003_hash_existing_passwords'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Family',
            new_name='Group',
        ),
        migrations.RenameField(
            model_name='person',
            old_name='family',
            new_name='group',
        ),
    ]
