# Generated by Django 6.0 on 2026-01-22 12:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gifts', '0004_user_subscriptions'),
    ]

    operations = [
        migrations.AddField(
            model_name='gift',
            name='percentage_mode',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='gift',
            name='price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True),
        ),
        migrations.AddField(
            model_name='reservation',
            name='brut_participation',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True),
        ),
        migrations.AddField(
            model_name='reservation',
            name='percentage_participation',
            field=models.IntegerField(default=100),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='gift',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reservation', to='gifts.gift'),
        ),
    ]
