# Generated by Django 6.0 on 2026-02-23 11:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gifts', '0005_gift_percentage_mode_gift_price_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='gift',
            name='percentage_mode',
        ),
        migrations.RemoveField(
            model_name='reservation',
            name='brut_participation',
        ),
        migrations.RemoveField(
            model_name='reservation',
            name='percentage_participation',
        ),
        migrations.AddField(
            model_name='gift',
            name='group_reserved_on',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reservations_group', to='gifts.group'),
        ),
        migrations.AddField(
            model_name='gift',
            name='offered',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='reservation',
            name='exclusivity',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='gift',
            name='price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=7, null=True),
        ),
    ]
