# Generated by Django 6.0 on 2025-12-19 11:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gifts', '0005_gift_created_by'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Person',
            new_name='User',
        ),
        migrations.RenameField(
            model_name='User',
            old_name='name',
            new_name='pseudo',
        ),
    ]
