# Generated by Django 6.0 on 2026-03-30 08:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gifts', '0006_remove_gift_percentage_mode_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='group',
            old_name='invite_token',
            new_name='group_token',
        ),
    ]
