# Generated by Django 6.0 on 2026-04-10 11:03

import django_resized.forms
import gifts.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gifts', '0008_group_description_group_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='avatar',
            field=django_resized.forms.ResizedImageField(blank=True, crop=['middle', 'center'], force_format=None, keep_meta=True, null=True, quality=80, scale=None, size=[200, 200], upload_to=gifts.models.get_avatar_path),
        ),
        migrations.AlterField(
            model_name='group',
            name='image',
            field=django_resized.forms.ResizedImageField(blank=True, crop=['middle', 'center'], force_format=None, keep_meta=True, null=True, quality=75, scale=None, size=[800, 600], upload_to=gifts.models.get_group_image_path),
        ),
    ]
