# Generated by Django 6.0 on 2026-04-19 14:07

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gifts', '0012_gift_offered_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='gift',
            name='actual_cost',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True),
        ),
        migrations.AddField(
            model_name='gift',
            name='expense_split',
            field=models.ManyToManyField(blank=True, related_name='split_gifts', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='group',
            name='show_balance',
            field=models.BooleanField(default=False),
        ),
        migrations.CreateModel(
            name='BalanceSettlement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=8)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='balance_settlements', to='gifts.group')),
                ('payee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='settlements_received', to=settings.AUTH_USER_MODEL)),
                ('payer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='settlements_made', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
