# Generated by Django 6.0 on 2026-04-19 17:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gifts', '0013_gift_actual_cost_gift_expense_split_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='group',
            name='show_history',
            field=models.BooleanField(default=False),
        ),
    ]
