# Generated by Django 6.0 on 2026-04-29 12:45

import django_resized.forms
import gifts.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gifts', '0014_group_history_disabled_by_default'),
    ]

    operations = [
        migrations.AlterField(
            model_name='group',
            name='image',
            field=django_resized.forms.ResizedImageField(blank=True, crop=['middle', 'center'], force_format=None, keep_meta=True, null=True, quality=75, scale=None, size=[1200, 400], upload_to=gifts.models.get_group_image_path),
        ),
    ]
