# Generated by Django 6.0 on 2026-04-30 09:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gifts', '0015_alter_group_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='ManagedMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('color', models.CharField(max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='managed_members', to='gifts.group')),
            ],
        ),
        migrations.AddField(
            model_name='gift',
            name='managed_member',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='gifts', to='gifts.managedmember'),
        ),
    ]
