# Generated by Django 6.0 on 2026-05-03 12:44

import django.db.models.deletion
import django.utils.timezone
import django_resized.forms
import gifts.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gifts', '0018_backfill_managed_member_users'),
    ]

    operations = [
        migrations.AddField(
            model_name='gift',
            name='is_hidden',
            field=models.BooleanField(default=False),
        ),
        migrations.CreateModel(
            name='EventList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('event_type', models.CharField(choices=[('wedding', 'Wedding list'), ('birth', 'Baby shower'), ('birthday', 'Birthday')], max_length=20)),
                ('description', models.TextField(blank=True)),
                ('event_date', models.DateField(blank=True, null=True)),
                ('image', django_resized.forms.ResizedImageField(blank=True, crop=['middle', 'center'], force_format=None, keep_meta=True, null=True, quality=75, scale=None, size=[1200, 400], upload_to=gifts.models.get_event_image_path)),
                ('access_token', models.CharField(blank=True, max_length=12, unique=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='event_lists', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='gift',
            name='event_list',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='gifts', to='gifts.eventlist'),
        ),
        migrations.CreateModel(
            name='GuestReservation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reserver_name', models.CharField(max_length=100)),
                ('session_key', models.CharField(blank=True, max_length=40)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('gift', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='guest_reservations', to='gifts.gift')),
                ('reserver_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='event_reservations', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'constraints': [models.UniqueConstraint(condition=models.Q(('reserver_user__isnull', False)), fields=('gift', 'reserver_user'), name='unique_user_event_reservation')],
            },
        ),
    ]
