# Generated by Django 6.0 on 2026-05-03 13:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gifts', '0019_eventlist_guestreservation_gift_event_fields'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='eventlist',
            name='event_type',
        ),
    ]
