# Generated by Django 6.0 on 2026-05-03 13:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gifts', '0020_remove_eventlist_event_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='guestreservation',
            name='exclusivity',
            field=models.BooleanField(default=False),
        ),
    ]
