# Generated by Django 6.0 on 2026-05-03 18:02

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gifts', '0021_guestreservation_exclusivity'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventlist',
            name='participants',
            field=models.ManyToManyField(blank=True, related_name='participating_event_lists', to=settings.AUTH_USER_MODEL),
        ),
    ]
