# Generated by Django 6.0 on 2026-07-08 09:44

import uuid

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


def migrate_existing_subscriptions(apps, schema_editor):
    User = apps.get_model("gifts", "User")
    Subscription = apps.get_model("gifts", "Subscription")
    old_through_model = User.subscriptions.through
    Subscription.objects.bulk_create(
        [
            Subscription(
                subscriber_id=link.from_user_id,
                owner_id=link.to_user_id,
                email_enabled=True,
                rss_enabled=False,
            )
            for link in old_through_model.objects.all().iterator()
        ]
    )


def restore_legacy_subscriptions(apps, schema_editor):
    User = apps.get_model("gifts", "User")
    Subscription = apps.get_model("gifts", "Subscription")
    old_through_model = User.subscriptions.through
    old_through_model.objects.bulk_create(
        [
            old_through_model(
                from_user_id=subscription.subscriber_id,
                to_user_id=subscription.owner_id,
            )
            for subscription in Subscription.objects.all().iterator()
        ]
    )


class Migration(migrations.Migration):

    dependencies = [
        ("gifts", "0023_user_managed_by"),
    ]

    operations = [
        migrations.CreateModel(
            name="Subscription",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("email_enabled", models.BooleanField(default=True)),
                ("rss_enabled", models.BooleanField(default=False)),
                (
                    "feed_token",
                    models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "owner",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="subscriber_records",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "subscriber",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="subscription_records",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.RunPython(migrate_existing_subscriptions, restore_legacy_subscriptions),
        migrations.RemoveField(
            model_name="user",
            name="subscriptions",
        ),
        migrations.AddField(
            model_name="user",
            name="subscriptions",
            field=models.ManyToManyField(
                blank=True,
                related_name="subscribers",
                through="gifts.Subscription",
                through_fields=("subscriber", "owner"),
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddConstraint(
            model_name="subscription",
            constraint=models.UniqueConstraint(
                fields=("subscriber", "owner"), name="unique_list_subscription"
            ),
        ),
    ]
