# Generated by Django 6.0 on 2026-08-20 11:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("gifts", "0035_gifttag_gift_tags"),
    ]

    operations = [
        migrations.AddField(
            model_name="gift",
            name="is_draft",
            field=models.BooleanField(default=False),
        ),
    ]
