name: Manual Release to Production

on:
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Copy docker-compose and nginx.conf to server
        uses: appleboy/scp-action@v0.1.7
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          source: "docker-compose.yml,nginx.conf"
          target: "~/app"

      - name: Update Production via SSH
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            cd ~/app
            
            echo "${{ secrets.GITHUB_TOKEN }}" | docker login ghcr.io -u ${{ github.actor }} --password-stdin
            
            cat << EOF > .env
            POSTGRES_PASSWORD=${{ secrets.POSTGRES_PASSWORD }}
            DJANGO_SECRET_KEY=${{ secrets.DJANGO_SECRET_KEY }}
            RESEND_API_KEY=${{ secrets.RESEND_API_KEY }}
            DEV=False
            EOF
            
            docker compose pull
            docker compose up -d --remove-orphans
            
            docker image prune -f